import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import java.text.SimpleDateFormat
import java.util.Date
import java.util.TimeZone

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.multiplatform")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.compose")
}

val ktorVersion = "3.0.3"

// App version, defined once and reused for both the Android manifest and the generated
// BuildInfo stamp (see generateBuildInfo below).
val appVersionName = "0.1.0"
val appVersionCode = 1

kotlin {
    // We use expect/actual *classes* (ClientTls); opt in to silence the Beta warning.
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        moduleName = "spawnerweb"
        browser {
            commonWebpackConfig {
                outputFileName = "spawnerweb.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        // The generated command list (see generateCommands below) is shared UI data.
        commonMain {
            kotlin.srcDir(layout.buildDirectory.dir("generated/commands"))
            // The build stamp (app version + git commit) generated by generateBuildInfo.
            kotlin.srcDir(layout.buildDirectory.dir("generated/buildinfo"))
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            // Material vector icons (Icons.Filled.*) — the shared UI uses these instead of
            // emoji glyphs so controls render on every target (the browser/Skiko has no
            // system emoji font). DCE/R8 strips the unused icons from each bundle.
            implementation(compose.materialIconsExtended)
            implementation(compose.ui)
            implementation(compose.components.uiToolingPreview)
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")
            // Multiplatform WebSocket transport + JSON (shared SpawnerClient/Protocol).
            implementation("io.ktor:ktor-client-core:$ktorVersion")
            implementation("io.ktor:ktor-client-websockets:$ktorVersion")
            implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
        }
        androidMain.dependencies {
            implementation("androidx.core:core-ktx:1.13.1")
            implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.6")
            implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.6")
            implementation("androidx.activity:activity-compose:1.9.3")
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")
            implementation(compose.uiTooling)
            // Ktor OkHttp engine (Android transport; brings okhttp transitively).
            implementation("io.ktor:ktor-client-okhttp:$ktorVersion")
        }
        wasmJsMain.dependencies {
            // Ktor Js engine → the browser's native WebSocket.
            implementation("io.ktor:ktor-client-js:$ktorVersion")
        }
        // JVM unit tests (`:app:testDebugUnitTest`) — home of the CommandsSyncTest
        // drift check (generated COMMANDS ↔ docs/commands.json).
        androidUnitTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

android {
    namespace = "com.bam.spawner"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.bam.spawner"
        minSdk = 26
        targetSdk = 35
        versionCode = appVersionCode
        versionName = appVersionName
    }

    // Kotlin Multiplatform maps its `androidMain` kotlin source set to the Android `main`
    // variant, but AGP still looks under src/main for the manifest/res — point it at androidMain.
    sourceSets.getByName("main") {
        manifest.srcFile("src/androidMain/AndroidManifest.xml")
        res.srcDirs("src/androidMain/res")
    }

    signingConfigs {
        // Pin the debug signing key when SPAWNER_DEBUG_KEYSTORE points at one, so
        // containerized builds (which otherwise mint a random debug key each time)
        // produce a stable signature and `adb install -r` upgrades in place.
        getByName("debug") {
            val ks = System.getenv("SPAWNER_DEBUG_KEYSTORE")
            if (ks != null && file(ks).exists()) {
                storeFile = file(ks)
                storePassword = "android"
                keyAlias = "androiddebugkey"
                keyPassword = "android"
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

// generateCommands turns the shared docs/commands.json (emitted from the server's
// authoritative command registry) into a Kotlin COMMANDS list, so the app's
// command reference + alias editor can never drift from the server grammar and
// no command can ship undocumented. Runs before every build.
val generateCommands by tasks.registering {
    val jsonFile = rootProject.file("../docs/commands.json")
    val outDir = layout.buildDirectory.dir("generated/commands").get().asFile
    inputs.file(jsonFile)
    outputs.dir(outDir)
    doLast {
        fun esc(s: String) = s.replace("\\", "\\\\").replace("\"", "\\\"")
        @Suppress("UNCHECKED_CAST")
        val data = groovy.json.JsonSlurper().parse(jsonFile) as Map<String, Any>
        @Suppress("UNCHECKED_CAST")
        val cmds = (data["commands"] as List<Map<String, Any>>)
            .sortedBy { it["title"] as String } // alphabetical, defensively (JSON is already sorted)
        val sb = StringBuilder()
        sb.appendLine("// GENERATED from docs/commands.json by the generateCommands Gradle task.")
        sb.appendLine("// Do not edit — change the server command registry and run `go run ./cmd/gencommands`.")
        sb.appendLine("package com.bam.spawner")
        sb.appendLine()
        sb.appendLine("/** One \"hey buddy\" command: display name, spoken phrasings, description. */")
        sb.appendLine("data class Command(val name: String, val aliases: List<String>, val description: String)")
        sb.appendLine()
        sb.appendLine("/** Every control command, alphabetical. Source of truth: server command registry. */")
        sb.appendLine("val COMMANDS: List<Command> = listOf(")
        for (c in cmds) {
            @Suppress("UNCHECKED_CAST")
            val aliases = (c["aliases"] as List<String>).joinToString(", ") { "\"${esc(it)}\"" }
            sb.appendLine("    Command(\"${esc(c["title"] as String)}\", listOf($aliases), \"${esc(c["description"] as String)}\"),")
        }
        sb.appendLine(")")
        val pkgDir = outDir.resolve("com/bam/spawner").apply { mkdirs() }
        pkgDir.resolve("Commands.kt").writeText(sb.toString())
    }
}

// generateBuildInfo stamps the shared UI with the app version + the git commit this
// bundle was built from, so an "About" page (and any device it's installed on) can
// report exactly which build is running. The commit is read straight out of `.git`
// (HEAD → ref → loose ref or packed-refs) with plain file I/O, so it works even in the
// containerized build image, which may not ship a `git` binary. Mirrors generateCommands.
val generateBuildInfo by tasks.registering {
    val gitDir = rootProject.file("../.git")
    val headFile = gitDir.resolve("HEAD")
    val outDir = layout.buildDirectory.dir("generated/buildinfo").get().asFile
    // Re-run only when the commit moves (HEAD/ref change) or the version bumps — keeps
    // the generated file (and its build timestamp) stable across no-op rebuilds.
    if (headFile.exists()) inputs.file(headFile)
    val packedRefs = gitDir.resolve("packed-refs")
    if (packedRefs.exists()) inputs.file(packedRefs)
    gitDir.resolve("refs/heads").let { if (it.isDirectory) inputs.dir(it) }
    inputs.property("versionName", appVersionName)
    inputs.property("versionCode", appVersionCode)
    outputs.dir(outDir)
    doLast {
        fun resolveCommit(): Pair<String, String> {
            if (!headFile.exists()) return "unknown" to "unknown"
            val head = headFile.readText().trim()
            if (!head.startsWith("ref:")) return head to "detached" // detached HEAD
            val ref = head.removePrefix("ref:").trim()
            val branch = ref.substringAfterLast('/')
            val looseRef = gitDir.resolve(ref)
            if (looseRef.exists()) return looseRef.readText().trim() to branch
            if (packedRefs.exists()) {
                packedRefs.readLines().forEach { line ->
                    if (line.endsWith(" $ref")) return line.substringBefore(' ').trim() to branch
                }
            }
            return "unknown" to branch
        }
        val (commit, branch) = resolveCommit()
        val shortCommit = if (commit.length >= 7) commit.substring(0, 7) else commit
        val buildTime = SimpleDateFormat("yyyy-MM-dd HH:mm 'UTC'").apply {
            timeZone = TimeZone.getTimeZone("UTC")
        }.format(Date())
        fun esc(s: String) = s.replace("\\", "\\\\").replace("\"", "\\\"")
        val sb = StringBuilder()
        sb.appendLine("// GENERATED by the generateBuildInfo Gradle task. Do not edit.")
        sb.appendLine("package com.bam.spawner")
        sb.appendLine()
        sb.appendLine("/** Build stamp: app version + the git commit this bundle was built from. */")
        sb.appendLine("object BuildInfo {")
        sb.appendLine("    const val versionName: String = \"${esc(appVersionName)}\"")
        sb.appendLine("    const val versionCode: Int = $appVersionCode")
        sb.appendLine("    const val gitCommit: String = \"${esc(commit)}\"")
        sb.appendLine("    const val gitCommitShort: String = \"${esc(shortCommit)}\"")
        sb.appendLine("    const val gitBranch: String = \"${esc(branch)}\"")
        sb.appendLine("    const val buildTime: String = \"${esc(buildTime)}\"")
        sb.appendLine("}")
        val pkgDir = outDir.resolve("com/bam/spawner").apply { mkdirs() }
        pkgDir.resolve("BuildInfo.kt").writeText(sb.toString())
    }
}

// Every Kotlin compilation (Android + wasmJs) needs the generated COMMANDS + BuildInfo sources present first.
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask<*>>().configureEach {
    dependsOn(generateCommands, generateBuildInfo)
}
